version: "3.8"
services:
  db:
    image: mysql:8.4
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rkeEIErZskcH
      MYSQL_USER: metrix_cad
      MYSQL_DATABASE: metrix_cad
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: metrix_cad_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: metrix_cad
      DB_PASSWORD: rkeEIErZskcH
      DB_NAME: metrix_cad
      JWT_SECRET: SISTEMA_CAD_METRIX_NETWORKS_2026_S3CR3T_K3Y
    depends_on:
      - db
volumes:
  mysql_data:
